### ISSUE TITLE
Generator Crash

### ISSUE THREAD

**Issue by fluky** [mattlewis92/generator-angular2-module#8]
Generator seems to crash at startup, before any prompts

```
$ yo angular2-module

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │       awe-inspiring      │
   `---------´   │ generator-angular2-modul │
    ( _´U`_ )    │       e generator!       │
    /___A___\   /╰──────────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: `email` required
    at module.exports (/usr/local/lib/node_modules/generator-angular2-module/node_modules/github-username/index.js:6:9)
    at Object.user.github.username (/usr/local/lib/node_modules/generator-angular2-module/node_modules/yeoman-generator/lib/actions/user.js:64:25)
    at /usr/local/lib/node_modules/generator-angular2-module/generators/app/index.js:16:24
    at module.exports.yeoman.Base.extend.prompting.githubUsernamePromise.then [as prompting] (/usr/local/lib/node_modules/generator-angular2-module/generators/app/index.js:15:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular2-module/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-angular2-module/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-angular2-module/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-angular2-module/node_modules/yeoman-generator/lib/base.js:440:9
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`
```

**Comment by mattlewis92** [comment]
Thanks, should be fixed in 1.4.1
